#! /bin/bash

level() {
    pactl list sinks | grep 'Volume: f' | awk '{print $5}' | sed 's/\%//g'
}

state() {
    amixer get Master | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq
}

if [[ $(state) == on ]]; then
    icon="on"
else
    icon="%{F#FFFF0000}off%{F-}"
fi

echo -n "Volume: $icon $(level)"
