#!/bin/sh
xset fp rehash
xsetroot -cursor_name left_ptr &

# set key board repeat rate
xset r rate 200 40 &
xmodmap ~/.xmodmap &

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
eval $(/usr/bin/gnome-keyring-daemon --start --components=secrets)

# set background
feh --bg-fill ~/pictures/wallpapers/revisions.png

exec bspwm -c ~/.bspwm/bspwmrc
