#!/bin/sh
xset fp rehash
xsetroot -cursor_name left_ptr &

# set key board repeat rate
xset r rate 200 40 &
xmodmap ~/.xmodmap &

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

exec bspwm -c ~/.bspwm/bspwmrc
