#!/bin/bash

bspc config border_width 2
bspc config window_gap 4
bspc config focus_follows_pointer true

bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio 0.50
bspc config pointer_modifier mod1  # alt

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 INVISemail

# Bar
# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch top bar
polybar top &

# Startup Shits
~/.bspwm/startup &
sxhkd -c ~/.sxhkd/sxhkdrc &

# Rules
bspc rule -a "Tresorit" state=floating
bspc rule -a "SpiderOakONE" state=floating
bspc rule -a "TeamViewer.exe" state=floating
bspc rule -a "*:Battle.net.exe" state=floating
bspc rule -a "*:postbox.exe" desktop=INVISemail
bspc rule -a "Nylas Mail" desktop=INVISemail
bspc rule -a "discord" desktop=^6
bspc rule -a "Slack" desktop=^2

bspc config external_rules_command ~/.bspwm/external_rules
