# Env setup. Done here instead of .zshenv because /etc/profile overwrites stuff

# Use emacs key bindings.
bindkey -e

# By default, zsh considers many characters part of a word (e.g., _ and -).
# Narrow that down to allow easier skipping through words via M-f and M-b.
export WORDCHARS='*?[]~&;!$%^<>'

export PATH=~/bin:$PATH
export EDITOR=nvim
export MANPAGER=less
export BROWSER=google-chrome-stable

# Python
export WORKON_HOME=$HOME/.venvs
export PROJECT_HOME=$HOME/projects
export VIRTUALENVWRAPPER_PROJECT_FILENAME=.venv
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
source /usr/bin/virtualenvwrapper_lazy.sh

# Ruby
export rvm_ignore_gemrc_issues=1
export PATH="$PATH:$HOME/.rvm/bin"

# tmux
export TMUXIFIER_LAYOUT_PATH=~/.tmux/layouts
export PATH=$PATH:~/.tmuxifier/bin
eval "$(tmuxifier init -)"

# bspwm
export BSPWM_SOCKET=/tmp/bspwm-socket
export SXHKD_SHELL=/bin/bash

# FZF
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git/"'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# FASD
export _FASD_MAX=5000
eval "$(fasd --init posix-alias zsh-hook)"

unset GREP_OPTIONS

# Plugins
source <(antibody init)
export NVM_LAZY_LOAD=true
antibody bundle lukechilds/zsh-nvm

eval "$(dircolors ~/.dir_colors/dircolors.ansi-light)"

# Auto completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"
autoload -U compinit
compinit

# Prompt
autoload -U promptinit colors && promptinit && colors
setopt promptsubst
source ~/.zsh_themes/ryan.zsh-theme

# History
HISTFILE=~/.zsh_history
SAVEHIST=20000
HISTSIZE=20000
setopt extended_history
setopt inc_append_history

# Edit current line
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# Filter based on what is already typed.
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

alias ls="ls --color=auto"
alias tmux="tmux -2"
alias ssh='TERM=xterm ssh'  # Nobody knows about poor termite...
alias pac='pacaur'

alias at="tmux attach -t "
alias load="tmuxifier load-session "
alias v='f -e nvim'
alias c='fasd_cd -d'
alias vim=nvim

alias sc-start="sudo systemctl start"
alias sc-restart="sudo systemctl restart"
alias sc-stop="sudo systemctl stop"
alias sc-enable="sudo systemctl enable"
alias sc-disable="sudo systemctl disable"

alias http="http --style=solarized"
